In [1]:
 # Create a constant array
		# Prints "[[ 7.  7.]
                #  [ 7.  7.]]"


import numpy as np
a = np.full((2, 2), 7)
a


array([[7, 7],
       [7, 7]])

In [2]:
# Create an array filled with random values
         # Might print "[[ 0.91940167  0.08143941]
         #               [ 0.68744134  0.87236687]]"

b=np.random.random((2, 2))
b

array([[0.64103824, 0.55422927],
       [0.29811528, 0.15449501]])

In [3]:
"""3. Create a NumPy array containing the numbers from 10 to 50. Display:

The array
Number of elements
Shape
Dimension
Data type
"""

c=np.arange(10, 51)
print("Array:", c)
print("Number of elements:", c.size)
print("Shape:", c.shape)
print("Dimension:", c.ndim)
print("Data type:", c.dtype)

Array: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
Number of elements: 41
Shape: (41,)
Dimension: 1
Data type: int64


In [7]:
"""4. Using NumPy, create:

A 1D array containing 10 zeros
A 3 × 3 array containing ones
A 4 × 4 identity matrix
An array containing numbers from 5 to 50 with a step size of 5.
""" 

d=np.zeros(10)
e=np.ones((3, 3))
f=np.eye(4)
g=np.arange(5, 51, 5)
d,e,f,g

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]),
 array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]))

In [8]:
"""5. Create an array containing numbers from 1 to 24. Reshape it into:

4 × 6
6 × 4
2 × 3 × 4

Display the shape and ndim of each result."""

a=np.arange(1, 25)
b=a.reshape(4, 6)
c=b.reshape(6, 4)
d=c.reshape(2, 3, 4)
print("4 x 6 array:\n", b)
print("Shape:", b.shape, "Dimension:", b.ndim)
print("\n6 x 4 array:\n", c)
print("Shape:", c.shape, "Dimension:", c.ndim)
print("\n2 x 3 x 4 array:\n", d)


4 x 6 array:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Shape: (4, 6) Dimension: 2

6 x 4 array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Shape: (6, 4) Dimension: 2

2 x 3 x 4 array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [9]:
"""6. Consider: marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])

Write NumPy statements to display:

First element
Last element
Third element
First four elements
Last three elements"""

marks = np.array([78, 85, 92, 67, 88, 73, 95, 81])
print("First element:", marks[0])
print("Last element:", marks[-1])
print("Third element:", marks[2])
print("First four elements:", marks[:4])
print("Last three elements:", marks[-3:])

First element: 78
Last element: 81
Third element: 92
First four elements: [78 85 92 67]
Last three elements: [73 95 81]


In [10]:
"""7. Create:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 10, 15, 20, 25])

Calculate:

a + b
a - b
a * b
a / b
Square of every element in a"""

a=np.array([10, 20, 30, 40, 50])
b=np.array([5, 10, 15, 20, 25])
print("a + b:", a + b)
print("a - b:", a - b)
print("a * b:", a * b)
print("a / b:", a / b)
print("Square of every element in a:", a ** 2)

a + b: [15 30 45 60 75]
a - b: [ 5 10 15 20 25]
a * b: [  50  200  450  800 1250]
a / b: [2. 2. 2. 2. 2.]
Square of every element in a: [ 100  400  900 1600 2500]
