In [3]:
import numpy as np

In [3]:
np.zeros((2,3))

array([1.,0.,0.],
      [0.,1.,0.],
      [0.,0.,1.])

NameError: name 'array' is not defined

In [4]:
np.array([1,2,3]*3)

array([1,2,3,1,2,3,1,2,3])

NameError: name 'array' is not defined

In [ ]:
np.hstack([p,2*p])



In [10]:
x=np.array([1,2,3])
y=np.array([4,5,6])

print(x + y)
print(x*y)
print(x**2)
print(x-y)
print(x@y)

[5 7 9]
[ 4 10 18]
[1 4 9]
[-3 -3 -3]
32


In [11]:
z=np.array([y,y**3])
z

array([[  4,   5,   6],
       [ 64, 125, 216]])

In [12]:
print(len(z))

2


In [ ]:
z.shape #Finding The Shape

(2, 3)

In [ ]:
#use .T to get transpose

z.T

#array([[  4,  64],
#       [  5, 125],
#       [  6, 216]])


array([[  4,  64],
       [  5, 125],
       [  6, 216]])

In [ ]:
z.dtype #.dtype to see type of elements on the array

dtype('int64')

In [ ]:
z=z.astype('f') #.astype to cast a specific type
z.dtype

dtype('float32')

In [ ]:
#Math fns
#Numpy has built in fns that can be used well

a=np.array([-4,-2,1,3,5])
a.sum()

#Output:np.int64(3)

np.int64(3)

In [ ]:
a.max() #.max() to find max value

np.int64(5)

In [19]:
a.min() #.min() to find min value

np.int64(-4)

In [20]:
a.mean() #.mean() to find mean value

np.float64(0.6)

In [21]:
a.std()

np.float64(3.2619012860600183)

In [22]:
a.argmax() #.argmax() to find index of max value

np.int64(4)

In [23]:
a.argmin() #.argmin() to find index of min value

np.int64(0)

In [ ]:
# Indexing/Slicing
s=np.arange(100)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [26]:
s=np.arange(6)**2
s

array([ 0,  1,  4,  9, 16, 25])

In [31]:
s=np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [27]:
#Use bracket notation to get specific elements
s[0],s[4],s[-1]


(np.int64(0), np.int64(16), np.int64(25))

In [28]:
#Use : to indicate a range of values, array[start:stop:step] where start is inclusive and stop is exclusive
s[1:5]

array([ 1,  4,  9, 16])

In [29]:
s[0:5:2] #start at index 0, stop at index 5, step by 2

array([ 0,  4, 16])

In [30]:
s[:3] #start at index 0, stop at index 3, step by 1

array([0, 1, 4])

In [4]:
r=np.arange(100)
r.resize((10,10)) #.resize() to change shape of array
r

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [5]:
# Use bracket notation to slice: array[row,column] where row and column can be a single index or a range of indices
r[2,4] #get the value at row 2, column 4

np.int64(24)

In [6]:
#2nd Example of slicing
r[0:5,0:5] #get the values from row 0 to 4 and column 0 to 4

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [ ]:
r[:3,:-1] #get the values from row 0 to 2 and column 0 to 8















array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [20, 21, 22, 23, 24, 25, 26, 27, 28]])